package dev.carlsen.flagkit

import androidx.compose.ui.graphics.vector.ImageVector
import dev.carlsen.flagkit.flagicons.AD
import dev.carlsen.flagkit.flagicons.AE
import dev.carlsen.flagkit.flagicons.AF
import dev.carlsen.flagkit.flagicons.AG
import dev.carlsen.flagkit.flagicons.AI
import dev.carlsen.flagkit.flagicons.AL
import dev.carlsen.flagkit.flagicons.AM
import dev.carlsen.flagkit.flagicons.AO
import dev.carlsen.flagkit.flagicons.AR
import dev.carlsen.flagkit.flagicons.AS
import dev.carlsen.flagkit.flagicons.AT
import dev.carlsen.flagkit.flagicons.AU
import dev.carlsen.flagkit.flagicons.AW
import dev.carlsen.flagkit.flagicons.AX
import dev.carlsen.flagkit.flagicons.AZ
import dev.carlsen.flagkit.flagicons.BA
import dev.carlsen.flagkit.flagicons.BB
import dev.carlsen.flagkit.flagicons.BD
import dev.carlsen.flagkit.flagicons.BE
import dev.carlsen.flagkit.flagicons.BF
import dev.carlsen.flagkit.flagicons.BG
import dev.carlsen.flagkit.flagicons.BH
import dev.carlsen.flagkit.flagicons.BI
import dev.carlsen.flagkit.flagicons.BJ
import dev.carlsen.flagkit.flagicons.BL
import dev.carlsen.flagkit.flagicons.BM
import dev.carlsen.flagkit.flagicons.BN
import dev.carlsen.flagkit.flagicons.BO
import dev.carlsen.flagkit.flagicons.BR
import dev.carlsen.flagkit.flagicons.BS
import dev.carlsen.flagkit.flagicons.BT
import dev.carlsen.flagkit.flagicons.BV
import dev.carlsen.flagkit.flagicons.BW
import dev.carlsen.flagkit.flagicons.BY
import dev.carlsen.flagkit.flagicons.BZ
import dev.carlsen.flagkit.flagicons.CA
import dev.carlsen.flagkit.flagicons.CC
import dev.carlsen.flagkit.flagicons.CD
import dev.carlsen.flagkit.flagicons.CF
import dev.carlsen.flagkit.flagicons.CG
import dev.carlsen.flagkit.flagicons.CH
import dev.carlsen.flagkit.flagicons.CI
import dev.carlsen.flagkit.flagicons.CK
import dev.carlsen.flagkit.flagicons.CL
import dev.carlsen.flagkit.flagicons.CM
import dev.carlsen.flagkit.flagicons.CN
import dev.carlsen.flagkit.flagicons.CO
import dev.carlsen.flagkit.flagicons.CR
import dev.carlsen.flagkit.flagicons.CU
import dev.carlsen.flagkit.flagicons.CV
import dev.carlsen.flagkit.flagicons.CW
import dev.carlsen.flagkit.flagicons.CX
import dev.carlsen.flagkit.flagicons.CY
import dev.carlsen.flagkit.flagicons.CZ
import dev.carlsen.flagkit.flagicons.DE
import dev.carlsen.flagkit.flagicons.DJ
import dev.carlsen.flagkit.flagicons.DK
import dev.carlsen.flagkit.flagicons.DM
import dev.carlsen.flagkit.flagicons.DO
import dev.carlsen.flagkit.flagicons.DZ
import dev.carlsen.flagkit.flagicons.EC
import dev.carlsen.flagkit.flagicons.EE
import dev.carlsen.flagkit.flagicons.EG
import dev.carlsen.flagkit.flagicons.ER
import dev.carlsen.flagkit.flagicons.ES
import dev.carlsen.flagkit.flagicons.ET
import dev.carlsen.flagkit.flagicons.EU
import dev.carlsen.flagkit.flagicons.FI
import dev.carlsen.flagkit.flagicons.FJ
import dev.carlsen.flagkit.flagicons.FK
import dev.carlsen.flagkit.flagicons.FM
import dev.carlsen.flagkit.flagicons.FO
import dev.carlsen.flagkit.flagicons.FR
import dev.carlsen.flagkit.flagicons.GA
import dev.carlsen.flagkit.flagicons.GB
import dev.carlsen.flagkit.flagicons.GB_ENG
import dev.carlsen.flagkit.flagicons.GB_NIR
import dev.carlsen.flagkit.flagicons.GB_SCT
import dev.carlsen.flagkit.flagicons.GB_WLS
import dev.carlsen.flagkit.flagicons.GB_ZET
import dev.carlsen.flagkit.flagicons.GD
import dev.carlsen.flagkit.flagicons.GE
import dev.carlsen.flagkit.flagicons.GF
import dev.carlsen.flagkit.flagicons.GG
import dev.carlsen.flagkit.flagicons.GH
import dev.carlsen.flagkit.flagicons.GI
import dev.carlsen.flagkit.flagicons.GL
import dev.carlsen.flagkit.flagicons.GM
import dev.carlsen.flagkit.flagicons.GN
import dev.carlsen.flagkit.flagicons.GP
import dev.carlsen.flagkit.flagicons.GQ
import dev.carlsen.flagkit.flagicons.GR
import dev.carlsen.flagkit.flagicons.GS
import dev.carlsen.flagkit.flagicons.GT
import dev.carlsen.flagkit.flagicons.GU
import dev.carlsen.flagkit.flagicons.GW
import dev.carlsen.flagkit.flagicons.GY
import dev.carlsen.flagkit.flagicons.HK
import dev.carlsen.flagkit.flagicons.HM
import dev.carlsen.flagkit.flagicons.HN
import dev.carlsen.flagkit.flagicons.HR
import dev.carlsen.flagkit.flagicons.HT
import dev.carlsen.flagkit.flagicons.HU
import dev.carlsen.flagkit.flagicons.ID
import dev.carlsen.flagkit.flagicons.IE
import dev.carlsen.flagkit.flagicons.IL
import dev.carlsen.flagkit.flagicons.IM
import dev.carlsen.flagkit.flagicons.IN
import dev.carlsen.flagkit.flagicons.IO
import dev.carlsen.flagkit.flagicons.IQ
import dev.carlsen.flagkit.flagicons.IR
import dev.carlsen.flagkit.flagicons.IS
import dev.carlsen.flagkit.flagicons.IT
import dev.carlsen.flagkit.flagicons.JE
import dev.carlsen.flagkit.flagicons.JM
import dev.carlsen.flagkit.flagicons.JO
import dev.carlsen.flagkit.flagicons.JP
import dev.carlsen.flagkit.flagicons.KE
import dev.carlsen.flagkit.flagicons.KG
import dev.carlsen.flagkit.flagicons.KH
import dev.carlsen.flagkit.flagicons.KI
import dev.carlsen.flagkit.flagicons.KM
import dev.carlsen.flagkit.flagicons.KN
import dev.carlsen.flagkit.flagicons.KP
import dev.carlsen.flagkit.flagicons.KR
import dev.carlsen.flagkit.flagicons.KW
import dev.carlsen.flagkit.flagicons.KY
import dev.carlsen.flagkit.flagicons.KZ
import dev.carlsen.flagkit.flagicons.LA
import dev.carlsen.flagkit.flagicons.LB
import dev.carlsen.flagkit.flagicons.LC
import dev.carlsen.flagkit.flagicons.LI
import dev.carlsen.flagkit.flagicons.LK
import dev.carlsen.flagkit.flagicons.LR
import dev.carlsen.flagkit.flagicons.LS
import dev.carlsen.flagkit.flagicons.LT
import dev.carlsen.flagkit.flagicons.LU
import dev.carlsen.flagkit.flagicons.LV
import dev.carlsen.flagkit.flagicons.LY
import dev.carlsen.flagkit.flagicons.MA
import dev.carlsen.flagkit.flagicons.MC
import dev.carlsen.flagkit.flagicons.MD
import dev.carlsen.flagkit.flagicons.ME
import dev.carlsen.flagkit.flagicons.MF
import dev.carlsen.flagkit.flagicons.MG
import dev.carlsen.flagkit.flagicons.MH
import dev.carlsen.flagkit.flagicons.MK
import dev.carlsen.flagkit.flagicons.ML
import dev.carlsen.flagkit.flagicons.MM
import dev.carlsen.flagkit.flagicons.MN
import dev.carlsen.flagkit.flagicons.MO
import dev.carlsen.flagkit.flagicons.MP
import dev.carlsen.flagkit.flagicons.MQ
import dev.carlsen.flagkit.flagicons.MR
import dev.carlsen.flagkit.flagicons.MS
import dev.carlsen.flagkit.flagicons.MT
import dev.carlsen.flagkit.flagicons.MU
import dev.carlsen.flagkit.flagicons.MV
import dev.carlsen.flagkit.flagicons.MW
import dev.carlsen.flagkit.flagicons.MX
import dev.carlsen.flagkit.flagicons.MY
import dev.carlsen.flagkit.flagicons.MZ
import dev.carlsen.flagkit.flagicons.NA
import dev.carlsen.flagkit.flagicons.NC
import dev.carlsen.flagkit.flagicons.NE
import dev.carlsen.flagkit.flagicons.NF
import dev.carlsen.flagkit.flagicons.NG
import dev.carlsen.flagkit.flagicons.NI
import dev.carlsen.flagkit.flagicons.NL
import dev.carlsen.flagkit.flagicons.NO
import dev.carlsen.flagkit.flagicons.NP
import dev.carlsen.flagkit.flagicons.NR
import dev.carlsen.flagkit.flagicons.NU
import dev.carlsen.flagkit.flagicons.NZ
import dev.carlsen.flagkit.flagicons.OM
import dev.carlsen.flagkit.flagicons.PA
import dev.carlsen.flagkit.flagicons.PE
import dev.carlsen.flagkit.flagicons.PF
import dev.carlsen.flagkit.flagicons.PG
import dev.carlsen.flagkit.flagicons.PH
import dev.carlsen.flagkit.flagicons.PK
import dev.carlsen.flagkit.flagicons.PL
import dev.carlsen.flagkit.flagicons.PM
import dev.carlsen.flagkit.flagicons.PN
import dev.carlsen.flagkit.flagicons.PR
import dev.carlsen.flagkit.flagicons.PS
import dev.carlsen.flagkit.flagicons.PT
import dev.carlsen.flagkit.flagicons.PW
import dev.carlsen.flagkit.flagicons.PY
import dev.carlsen.flagkit.flagicons.QA
import dev.carlsen.flagkit.flagicons.RE
import dev.carlsen.flagkit.flagicons.RO
import dev.carlsen.flagkit.flagicons.RS
import dev.carlsen.flagkit.flagicons.RU
import dev.carlsen.flagkit.flagicons.RW
import dev.carlsen.flagkit.flagicons.SA
import dev.carlsen.flagkit.flagicons.SB
import dev.carlsen.flagkit.flagicons.SC
import dev.carlsen.flagkit.flagicons.SD
import dev.carlsen.flagkit.flagicons.SE
import dev.carlsen.flagkit.flagicons.SG
import dev.carlsen.flagkit.flagicons.SH
import dev.carlsen.flagkit.flagicons.SI
import dev.carlsen.flagkit.flagicons.SJ
import dev.carlsen.flagkit.flagicons.SK
import dev.carlsen.flagkit.flagicons.SL
import dev.carlsen.flagkit.flagicons.SM
import dev.carlsen.flagkit.flagicons.SN
import dev.carlsen.flagkit.flagicons.SO
import dev.carlsen.flagkit.flagicons.SR
import dev.carlsen.flagkit.flagicons.SS
import dev.carlsen.flagkit.flagicons.ST
import dev.carlsen.flagkit.flagicons.SV
import dev.carlsen.flagkit.flagicons.SX
import dev.carlsen.flagkit.flagicons.SY
import dev.carlsen.flagkit.flagicons.SZ
import dev.carlsen.flagkit.flagicons.TC
import dev.carlsen.flagkit.flagicons.TD
import dev.carlsen.flagkit.flagicons.TF
import dev.carlsen.flagkit.flagicons.TG
import dev.carlsen.flagkit.flagicons.TH
import dev.carlsen.flagkit.flagicons.TJ
import dev.carlsen.flagkit.flagicons.TK
import dev.carlsen.flagkit.flagicons.TL
import dev.carlsen.flagkit.flagicons.TM
import dev.carlsen.flagkit.flagicons.TN
import dev.carlsen.flagkit.flagicons.TO
import dev.carlsen.flagkit.flagicons.TR
import dev.carlsen.flagkit.flagicons.TT
import dev.carlsen.flagkit.flagicons.TV
import dev.carlsen.flagkit.flagicons.TW
import dev.carlsen.flagkit.flagicons.TZ
import dev.carlsen.flagkit.flagicons.UA
import dev.carlsen.flagkit.flagicons.UG
import dev.carlsen.flagkit.flagicons.UM
import dev.carlsen.flagkit.flagicons.US
import dev.carlsen.flagkit.flagicons.US_CA
import dev.carlsen.flagkit.flagicons.UY
import dev.carlsen.flagkit.flagicons.UZ
import dev.carlsen.flagkit.flagicons.VA
import dev.carlsen.flagkit.flagicons.VC
import dev.carlsen.flagkit.flagicons.VE
import dev.carlsen.flagkit.flagicons.VG
import dev.carlsen.flagkit.flagicons.VI
import dev.carlsen.flagkit.flagicons.VN
import dev.carlsen.flagkit.flagicons.VU
import dev.carlsen.flagkit.flagicons.WF
import dev.carlsen.flagkit.flagicons.WS
import dev.carlsen.flagkit.flagicons.XK
import dev.carlsen.flagkit.flagicons.YE
import dev.carlsen.flagkit.flagicons.YT
import dev.carlsen.flagkit.flagicons.ZA
import dev.carlsen.flagkit.flagicons.ZM
import dev.carlsen.flagkit.flagicons.ZW
import kotlin.collections.List as ____KtList

object FlagIcons

private var __AllIcons: ____KtList<ImageVector>? = null

val FlagIcons.AllIcons: ____KtList<ImageVector>
  get() {
    if (__AllIcons != null) {
      return __AllIcons!!
    }
    __AllIcons= listOf(AD, AE, AF, AG, AI, AL, AM, AO, AR, AS, AT, AU, AW, AX, AZ, BA, BB, BD, BE,
        BF, BG, BH, BI, BJ, BL, BM, BN, BO, BR, BS, BT, BV, BW, BY, BZ, CA, CC, CD, CF, CG, CH, CI,
        CK, CL, CM, CN, CO, CR, CU, CV, CW, CX, CY, CZ, DE, DJ, DK, DM, DO, DZ, EC, EE, EG, ER,
        ES, ET, EU, FI, FJ, FK, FM, FO, FR, GA, GB, GB_ENG, GB_NIR, GB_SCT, GB_WLS, GB_ZET, GD, GE, GF, GG, GH, GI, GL,
        GM, GN, GP, GQ, GR, GS, GT, GU, GW, GY, HK, HM, HN, HR, HT, HU, ID, IE, IL, IM, IN, IO,
        IQ, IR, IS, IT, JE, JM, JO, JP, KE, KG, KH, KI, KM, KN, KP, KR, KW, KY, KZ, LA, LB, LC, LI,
        LK, LR, LS, LT, LU, LV, LY, MA, MC, MD, ME, MF, MG, MH, MK, ML, MM, MN, MO, MP, MQ, MR,
        MS, MT, MU, MV, MW, MX, MY, MZ, NA, NC, NE, NF, NG, NI, NL, NO, NP, NR, NU, NZ, OM, PA,
        PE, PF, PG, PH, PK, PL, PM, PN, PR, PS, PT, PW, PY, QA, RE, RO, RS, RU, RW, SA, SB, SC, SD,
        SE, SG, SH, SI, SJ, SK, SL, SM, SN, SO, SR, SS, ST, SV, SX, SY, SZ, TC, TD, TF, TG, TH,
        TJ, TK, TL, TM, TN, TO, TR, TT, TV, TW, TZ, UA, UG, UM, US, US_CA, UY, UZ, VA, VC, VE, VG, VI,
        VN, VU, WF, WS, XK, YE, YT, ZA, ZM, ZW)
    return __AllIcons!!
  }
