name: Build

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: "Setup Gradle Dependencies Cache"
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle-wrapper.properties') }}

      - name: "Run tests"
        run: ./gradlew desktopTest

      - name: "Test Summary"
        uses: test-summary/action@v2
        with:
          paths: |
            core/build/test-results/**/TEST-*.xml
        if: always()
